
import 'package:fincabay_application/configs/colors.dart';
import 'package:flutter/material.dart';

const TextStyle titleStyle=TextStyle(fontSize: 20.0,fontWeight: FontWeight.bold,color: blackColor);
const TextStyle labelStyle1=TextStyle(color: greenColor,fontSize: 14.0);
const TextStyle labelStyle2=TextStyle(color: blackColor,fontSize: 14.0);
const TextStyle forgotStyle=TextStyle(color: lightBlackColor,fontSize: 14.0);
const TextStyle barStyle=TextStyle(color: whiteColor,fontWeight: FontWeight.bold,fontSize: 18.0);
const TextStyle headerStyle=TextStyle(color: blackColor,fontSize: 14.0,fontWeight: FontWeight.w500);
const TextStyle countryStyle=TextStyle(color: blackColor, fontSize: 16.0, height: 1.25);
const TextStyle propertyStyle=TextStyle(color: blackColor, fontSize: 15.0, height: 1.25,fontWeight: FontWeight.w700);
const TextStyle ddStyle=TextStyle(color: blackColor, fontSize: 16.0);
const TextStyle passwordStyle=TextStyle(color: blackColor,fontWeight: FontWeight.bold,fontSize: 28.0,height: 2.2);
const TextStyle logoStyle=TextStyle(fontSize: 20.0,fontWeight: FontWeight.bold,color: blackColor,height: 2.0);
const TextStyle nameStyle=TextStyle(color: bgColor,fontSize: 18.0,fontWeight: FontWeight.w700,height: 1.2);
const TextStyle pkrStyle=TextStyle(color: blackColor,fontSize: 16.0,fontWeight: FontWeight.w500,height: 1.6);
const TextStyle addressStyle=TextStyle(color: blackColor,fontSize: 16.0,fontWeight: FontWeight.w500,);
const TextStyle houseStyle=TextStyle(color: black26,fontSize: 14.0,height: 1.5);
const TextStyle imageStyle=TextStyle(color: blackColor,fontSize: 16.0,fontWeight: FontWeight.w500,height: 1.8);
const TextStyle cameraStyle=TextStyle(color: bgColor);
const TextStyle locationStyle=TextStyle(color: lightBlackColor,fontSize: 14.0,height: 1.3);
const TextStyle iconStyle=TextStyle(color: lightBlackColor,fontSize: 14.0,height: 1.7);
const TextStyle propertyNameStyle=TextStyle(color: Colors.green,fontSize: 14.0,fontWeight: FontWeight.w500);
const TextStyle priceStyle=TextStyle(color: pkrColor,fontSize: 20.0,fontWeight: FontWeight.w700,height: 1.5);
const TextStyle lessStyle=TextStyle(color: bgColor,fontSize: 14.0,fontWeight: FontWeight.w600);
const TextStyle pKrStyle=TextStyle(color: blackColor,fontSize: 10.0,fontWeight: FontWeight.w500,);
const TextStyle loginStyle=TextStyle(color: blackColor,fontWeight: FontWeight.w700,fontSize: 18.0,);
const TextStyle addPropStyle=TextStyle(color: lightBlackColor,fontSize: 16.0,fontWeight: FontWeight.bold);
const TextStyle profileStyle=TextStyle(fontSize: 24.0,fontWeight: FontWeight.bold,color: blackColor);
const TextStyle contactStyle=TextStyle(color: blackColor,fontSize: 14.0,fontWeight: FontWeight.w600);
const TextStyle userStyle=TextStyle(color: blackColor,fontWeight: FontWeight.w700,fontSize: 18.0,height: 2.0);
const TextStyle noStyle=TextStyle(fontSize: 13.0);
const TextStyle sellStyle=TextStyle(color: blackColor,fontSize: 14.0,fontWeight: FontWeight.bold);
const TextStyle accountsStyle=TextStyle(color: lightBlackColor,fontSize: 16.0,height: 2.5);
const TextStyle lengthStyle=TextStyle(color: whiteColor,fontSize: 14.0,fontWeight: FontWeight.w500);
const TextStyle accStyle=TextStyle(color: Colors.black45, fontSize: 14.0, height: 2.3);
const TextStyle signUpStyle=TextStyle(color: lightBlackColor, fontSize: 14.0, fontWeight: FontWeight.w800);